import { TeacherPageState } from './state';
import {
  OPEN_ADD_TEACHER_MODAL,
  CLOSE_ADD_TEACHER_MODAL,
  SEARCH_CHANGE,
  CREATE_NEW_TEACHER,
  CREATE_NEW_TEACHER_SUCCESS,
  UPDATE_TEACHER,
  UPDATE_TEACHER_SUCCESS,
  TEACHER_INFO_CHANGE,
  FETCH_DATA,
  FILTER_CHANGE,
  ERROR_HAPPEN,
  STARTING,
  FETCH_DATA_SUCCESS,
  ACTIVATE_TEACHER,
  DEACTIVATE_TEACHER,
  ACTIVATE_TEACHER_SUCCESS,
  DEACTIVATE_TEACHER_SUCCESS,
  openAddTeacherModal,
  closeAddTeacherModal,
  searchChange,
  createNewTeacher,
  createNewTeacherSuccess,
  updateTeacher,
  updateTeacherSuccess,
  teacherInfoChange,
  fetchData,
  filterChange,
  errorHappen,
  starting,
  fetchDataSuccess,
  activateTeacher,
  deactivateTeacher,
  activateTeacherSuccess,
  deactivateTeacherSuccess,
} from './action';
import { teacherPageReducer } from './reducer';
import teacherPageSaga from './saga';

export {
  // State
  TeacherPageState,

  // Action
  OPEN_ADD_TEACHER_MODAL,
  CLOSE_ADD_TEACHER_MODAL,
  SEARCH_CHANGE,
  CREATE_NEW_TEACHER,
  CREATE_NEW_TEACHER_SUCCESS,
  UPDATE_TEACHER,
  UPDATE_TEACHER_SUCCESS,
  TEACHER_INFO_CHANGE,
  FETCH_DATA,
  FILTER_CHANGE,
  ERROR_HAPPEN,
  STARTING,
  FETCH_DATA_SUCCESS,
  ACTIVATE_TEACHER,
  DEACTIVATE_TEACHER,
  ACTIVATE_TEACHER_SUCCESS,
  DEACTIVATE_TEACHER_SUCCESS,
  openAddTeacherModal,
  closeAddTeacherModal,
  searchChange,
  createNewTeacher,
  createNewTeacherSuccess,
  updateTeacher,
  updateTeacherSuccess,
  teacherInfoChange,
  fetchData,
  filterChange,
  errorHappen,
  starting,
  fetchDataSuccess,
  activateTeacher,
  deactivateTeacher,
  activateTeacherSuccess,
  deactivateTeacherSuccess,

  // Saga
  teacherPageSaga,

  // Reducer
  teacherPageReducer,
};
